# file input *.csv in the format:
'''
NREC;IDPERS;COGNOME;NOME;NATO A;DATA NS;RESIDENTE A;PROVINCIA;VIA;CAP;CODFISC;
CITTADINANZA1;CITTADINANZA2;NAZIONE_RS;MAIL;IBAN;SWIFT_BIC;TIPO_IBAN;BANCA_NOME;
BANCA_INDIRIZZO;BANCA_NAZIONE;INTESTATARIO_COGNOME;INTESTATARIO_NOME;INTESTATARIO_CF;
ASSE. COMPLESSO;ASSE. STABILE;ASSE. PIANO;ASSE. ELEMENTO;ASSE. TIPO ALLG.;
ASSE. ALLOGGIO;ASSE. POSTO_LETTO;ASSE. DATA_ING;ASSE. DATA_UN;ASSE. DATA_ARRIVO;
ASSE. CHECKIN;ASSE. CHECKOUT;ASSE. NOTE;ASSE. PROTOCOLLO;CONTROLLO AUTO.;
AUTORIZZAZIONE;AUT. DESCR;AUT. DETT.;AUT. DETT. DESCR;AUT. VALIDO_DAL;
AUT. VALIDO_AL;AUT. NOTE
'''

# date in format:
# yyyy-mm-dd

from library import days_for_month


def test_days_is_int():
    cases = [('2023-09-18', '2023-09-30', 13),
             ('2023-10-01', '2023-10-31', 31),
             ('2023-11-01', '2023-11-30', 30)]

    result = 0

    for case in cases:
        result = days_for_month.days(case[0], case[1])

        assert result == case[2]
